version: '3.8'

services:
    stock-api:
        image: ghcr.io/ozon-edu-csharp-2021/stock-api:main
        hostname: stock-api
        ports:
            - "8080:80"
        depends_on:
            - redis
    redis:
        image: redis
        hostname: redis